version: '3'

services:
 jenkins:
  image: jenkins-docker-access:latest
  container_name: jda
  ports:
   - "8001:8080"
   - "50000:50000"
  volumes:
   - /var/lib/jenkins/data:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
   - /var/jenkins_home/plugins:/var/jenkins_home/plugins
   - ./jenkins-env:/home/jenkins-env
  environment:
   - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
  networks:
   - shiny-jenkins


 registry:
  image: registry:latest
  container_name: registry
  ports:
   - 5000:5000
  networks:
   - shiny-jenkins

networks:
  shiny-jenkins:
   name: shiny-jenkins
  