pipeline {
    agent {
        docker { image 'mvn-loaded:latest' }
    }
    stages {
        stage('cloning ...') {
            steps {
                git url: 'https://github.com/thingsboard/thingsboard.git', branch: 'master'
            }
        }
        stage('building ...') {
            steps {
                sh ' mvn -T 4 clean install -DskipTests --fail-at-end -Dlicense.skip=true'
            }
        }
    }
}
