pipeline {
    agent {
        docker { image 'mvn-loaded:latest' }
    }
    stages {
        stage('check-version') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}
