FROM maven:3.9.2-amazoncorretto-11-debian-bullseye

USER root

# install required tools
RUN apt update
RUN apt upgrade -y
RUN apt install unzip -y
RUN apt install zip -y
RUN apt install curl -y
RUN apt install wget -y

# install gradle
RUN wget https://downloads.gradle-dn.com/distributions/gradle-7.1.1-bin.zip
RUN unzip gradle-7.1.1-bin.zip
ENV GRADLE_HOME /gradle-7.1.1
ENV PATH $PATH:/gradle-7.1.1/bin
RUN gradle --version

# install node 16.15
RUN apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install -y nodejs
RUN node --version

# install yarn
RUN npm install --global yarn
RUN yarn --version

# install Git
RUN apt install git -y

# Install dig for service discovery
RUN apt install dnsutils -y

# Install docker CLI
RUN curl -sSL https://get.docker.com/ | sh

WORKDIR /

# Container will be alive after lanch
ENTRYPOINT ["tail", "-f", "/dev/null"]
